runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: trigramosaurus.app
libraries:
- name: PIL
  version: "1.1.7"
- name: lxml
  version: "3.7.3"
- name: ssl
  version: "2.7.11"
